# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name transcription
POST http://localhost:3333/videos/3518764d-fc4e-4fe1-b2e4-0e0ccd9e55a5/transcription
Content-Type: application/json

{
    "prompt": "Clean Architecture com DDD"
}

###

# @name generate AI completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "3518764d-fc4e-4fe1-b2e4-0e0ccd9e55a5", 
    "temperature": 0.2,
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}
